language: python
sudo: required
dist: xenial
python:
  - "3.7"
#  - "nightly"
before_install:
  - "export DISPLAY=:99.0"
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script:
 - isort -c -rc
 - pycodestyle pylottosimu/ tests/ *.py*
 - xvfb-run nosetests --with-coverage --cover-erase --cover-package=pylottosimu --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=c7c5048f9c0e4b74b529f9b72671c5cf
  - python-codacy-coverage -r coverage.xml
notifications:
  irc: false
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fdaa9e93e1a5b657bed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
