language: python
os: linux
dist: bionic
services:
  - xvfb
python:
  - "3.9"
#  - "nightly"
addons:
  apt:
    packages:
    - libxkbcommon-x11-0
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
 - isort . --diff
 - pycodestyle pylottosimu/ tests/ *.py*
 - nosetests --with-coverage --cover-erase --cover-package=pylottosimu --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=c7c5048f9c0e4b74b529f9b72671c5cf
  - python-codacy-coverage -r coverage.xml
notifications:
  irc: false
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fdaa9e93e1a5b657bed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
