language: python
sudo: required
dist: xenial
python:
  - "3.7"
#  - "nightly"
addons:
  apt:
    packages:
    - libxkbcommon-x11-0
before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3
before_script:
  - "herbstluftwm &"
  - sleep 1
script:
 - isort -c -rc
 - pycodestyle pylottosimu/ tests/ *.py*
 - nosetests --with-coverage --cover-erase --cover-package=pylottosimu --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=c7c5048f9c0e4b74b529f9b72671c5cf
  - python-codacy-coverage -r coverage.xml
notifications:
  irc: false
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fdaa9e93e1a5b657bed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
