files:
  - source: /docs/_build/locale/*.pot
    translation: /docs/locale/%two_letters_code%/LC_MESSAGES/%file_name%.po
  - source: /pylottosimu/translation/lotto1.ts
    translation: /pylottosimu/translation/lotto1.%two_letters_code%.ts
