# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotto.ui'
#
# Created: Mon Apr  2 23:00:44 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 368)
        self.Lottozahlen = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lottozahlen.sizePolicy().hasHeightForWidth())
        self.Lottozahlen.setSizePolicy(sizePolicy)
        self.Lottozahlen.setMinimumSize(QtCore.QSize(480, 320))
        self.Lottozahlen.setMaximumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lottozahlen.setFont(font)
        self.Lottozahlen.setAutoFillBackground(False)
        self.Lottozahlen.setStyleSheet(_fromUtf8("QFrame#Rahmen { border-image: url(:/lottokugel.png)}\n"
"QLabel {    background-color: rgb(220, 220, 220)}\n"
"QLabel#label_zahl {    background-color: none}"))
        self.Lottozahlen.setObjectName(_fromUtf8("Lottozahlen"))
        self.Rahmen = QtGui.QFrame(self.Lottozahlen)
        self.Rahmen.setEnabled(True)
        self.Rahmen.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.Rahmen.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Rahmen.setFrameShadow(QtGui.QFrame.Raised)
        self.Rahmen.setObjectName(_fromUtf8("Rahmen"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.Rahmen)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 20, 441, 16))
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_Lottozahlen = QtGui.QLabel(self.Rahmen)
        self.label_Lottozahlen.setGeometry(QtCore.QRect(20, 0, 441, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_Lottozahlen.setFont(font)
        self.label_Lottozahlen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lottozahlen.setObjectName(_fromUtf8("label_Lottozahlen"))
        self.layoutWidget = QtGui.QWidget(self.Rahmen)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 140, 351, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.anzahl = QtGui.QSpinBox(self.layoutWidget)
        self.anzahl.setMinimum(1)
        self.anzahl.setMaximum(15)
        self.anzahl.setProperty("value", 6)
        self.anzahl.setObjectName(_fromUtf8("anzahl"))
        self.horizontalLayout.addWidget(self.anzahl)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.hochste = QtGui.QSpinBox(self.layoutWidget)
        self.hochste.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.hochste.setMinimum(20)
        self.hochste.setMaximum(90)
        self.hochste.setSingleStep(1)
        self.hochste.setProperty("value", 49)
        self.hochste.setObjectName(_fromUtf8("hochste"))
        self.horizontalLayout.addWidget(self.hochste)
        self.Zufallsgenerator = QtGui.QPushButton(self.Rahmen)
        self.Zufallsgenerator.setGeometry(QtCore.QRect(150, 260, 181, 31))
        self.Zufallsgenerator.setObjectName(_fromUtf8("Zufallsgenerator"))
        self.AusgfeldLeeren = QtGui.QPushButton(self.Rahmen)
        self.AusgfeldLeeren.setGeometry(QtCore.QRect(160, 180, 161, 25))
        self.AusgfeldLeeren.setObjectName(_fromUtf8("AusgfeldLeeren"))
        self.label_zahl = QtGui.QLabel(self.Rahmen)
        self.label_zahl.setEnabled(True)
        self.label_zahl.setGeometry(QtCore.QRect(170, 20, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_zahl.setFont(font)
        self.label_zahl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zahl.setObjectName(_fromUtf8("label_zahl"))
        self.btn_start = QtGui.QPushButton(self.Rahmen)
        self.btn_start.setGeometry(QtCore.QRect(180, 110, 121, 25))
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.horizontalSlider = QtGui.QSlider(self.Rahmen)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 50, 91, 20))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(99)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(True)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_Geschwindigkeit = QtGui.QLabel(self.Rahmen)
        self.label_Geschwindigkeit.setGeometry(QtCore.QRect(15, 80, 101, 20))
        self.label_Geschwindigkeit.setObjectName(_fromUtf8("label_Geschwindigkeit"))
        MainWindow.setCentralWidget(self.Lottozahlen)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuModus = QtGui.QMenu(self.menubar)
        self.menuModus.setObjectName(_fromUtf8("menuModus"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionZufallsgenerator = QtGui.QAction(MainWindow)
        self.actionZufallsgenerator.setCheckable(True)
        self.actionZufallsgenerator.setChecked(True)
        self.actionZufallsgenerator.setObjectName(_fromUtf8("actionZufallsgenerator"))
        self.actionLottosimulation = QtGui.QAction(MainWindow)
        self.actionLottosimulation.setCheckable(True)
        self.actionLottosimulation.setChecked(True)
        self.actionLottosimulation.setObjectName(_fromUtf8("actionLottosimulation"))
        self.actionHilfe = QtGui.QAction(MainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionInfo)
        self.menuModus.addAction(self.actionLottosimulation)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuModus.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.anzahl, self.hochste)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyLottoSimu", None, QtGui.QApplication.UnicodeUTF8))
        self.Lottozahlen.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Lottozahlen.setText(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Zahlen:", None, QtGui.QApplication.UnicodeUTF8))
        self.anzahl.setToolTip(QtGui.QApplication.translate("MainWindow", "Anzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.anzahl.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Anzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.anzahl.setAccessibleName(QtGui.QApplication.translate("MainWindow", "Anzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "aus", None, QtGui.QApplication.UnicodeUTF8))
        self.hochste.setToolTip(QtGui.QApplication.translate("MainWindow", "Höchste Zufallszahl", None, QtGui.QApplication.UnicodeUTF8))
        self.hochste.setStatusTip(QtGui.QApplication.translate("MainWindow", "Höchste Zufallszahl", None, QtGui.QApplication.UnicodeUTF8))
        self.hochste.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Höchste Zufallszahl", None, QtGui.QApplication.UnicodeUTF8))
        self.Zufallsgenerator.setToolTip(QtGui.QApplication.translate("MainWindow", "Zufallsgenerator ein", None, QtGui.QApplication.UnicodeUTF8))
        self.Zufallsgenerator.setStatusTip(QtGui.QApplication.translate("MainWindow", "Zufallsgenerator ein", None, QtGui.QApplication.UnicodeUTF8))
        self.Zufallsgenerator.setText(QtGui.QApplication.translate("MainWindow", "Zufallsgenerator ein", None, QtGui.QApplication.UnicodeUTF8))
        self.AusgfeldLeeren.setToolTip(QtGui.QApplication.translate("MainWindow", "Ausgabefeld leeren", None, QtGui.QApplication.UnicodeUTF8))
        self.AusgfeldLeeren.setText(QtGui.QApplication.translate("MainWindow", "Ausgabefeld leeren", None, QtGui.QApplication.UnicodeUTF8))
        self.label_zahl.setText(QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setToolTip(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalSlider.setStatusTip(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Geschwindigkeit.setText(QtGui.QApplication.translate("MainWindow", "Geschwindigkeit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.menuModus.setTitle(QtGui.QApplication.translate("MainWindow", "Modus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZufallsgenerator.setText(QtGui.QApplication.translate("MainWindow", "Zufallsgenerator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLottosimulation.setText(QtGui.QApplication.translate("MainWindow", "Lottosimulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe.setText(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))

import lottokugeln_rc
